global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Snowflake ID generator metrics
  - job_name: 'snowflake'
    scrape_interval: 10s
    static_configs:
      - targets: ['snowflake:8080']
        labels:
          service: 'snowflake-generator'
          environment: 'development'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
